### ISSUE TITLE
batch

### ISSUE THREAD

**Issue by kiellaurence** [PinakaMalupetnaServer/ChristmasPMnS#2]
[Server thread/CRITICAL]: UnexpectedValueException: "Too many packets in a single batch" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket" at line 101

**Comment by Lycol50** [comment]
Please Check again this repository, I have updated it.
One of the reasons of that because of multiple packets have been sent, i have tested it then this error appears, to fix this i need to control the delay on LaunchTask.php
